import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.expense}>
          <div className={styles.expense__left}>
            <p>My balance</p>
            <p className="balance">$900</p>
          </div>
          <img src="/images/logo.svg"></img>
        </div>
        <div className={styles.history}>
          <h2>Spending last 7 days</h2>
          <div className="chart"></div>
          <div className={styles.history__month}>
            <div className="history__month__this">
              <p>Total this month</p>
              <p>$470</p>
            </div>
            <div className="history__month__last">
              <p>%</p>
              <p>From last month</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
