import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useMemo } from "react";
import Column from "../components/collumn";

type spendingPerDay = {
  day: string;
  value: number;
};

const Home: NextPage = ({ data }) => {
  const graph = useMemo(() => {
    let max = Math.max(...data.map((element) => element.amount));
    return data.map((element, index) => (
      <Column
        day={element.day}
        biggest={element.amount === max}
        amount={element.amount}
        key={index}
      />
    ));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.expense}>
          <div className={styles.expense__left}>
            <p>My balance</p>
            <p className={styles.balance}>$900</p>
          </div>
          <img src="/images/logo.svg"></img>
        </div>
        <div className={styles.history}>
          <h2>Spending last 7 days</h2>
          <div className="chart">
            <div className={styles.graph}>{graph}</div>
          </div>
          <div className={styles.history__month}>
            <div className="history__month__this">
              <p className={styles.month__text}>Total this month</p>
              <p>$470</p>
            </div>
            <div className={styles.history__month__last}>
              <p>2.4%</p>
              <p className={styles.month__text}>From last month</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  let res = await fetch("http:localhost:3000/api/data");
  let data = await res.json();

  return {
    props: { data }, // will be passed to the page component as props
  };
}

export default Home;
