import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useMemo } from "react";
import Column from "../components/collumn";

type spendingPerDay = {
  day: string;
  amount: number;
};

const Home = ({ data }: { data: spendingPerDay[] }) => {
  const graph = useMemo(() => {
    let max = Math.max(
      ...data.map((element: spendingPerDay) => element.amount)
    );
    return data.map((element: spendingPerDay, index: number) => (
      <Column
        day={element.day}
        biggest={element.amount === max}
        amount={element.amount}
        key={index}
      />
    ));
  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.expense}>
          <div className={styles.expense__left}>
            <p className={styles.expense__text}>My balance</p>
            <p className={styles.balance}>$921.48</p>
          </div>
          <img alt="logo" src="/images/logo.svg"></img>
        </div>
        <div className={styles.history}>
          <h2>Spending last 7 days</h2>
          <div className={styles.chart}>
            <div className={styles.graph}>{graph}</div>
          </div>
          <div className={styles.history__month}>
            <div className="history__month__this">
              <p className={styles.month__text}>Total this month</p>
              <p className={styles.month__spending}>$478.33</p>
            </div>
            <div className={styles.history__month__last}>
              <p className={styles.last__month__percentage}>+2.4%</p>
              <p className={styles.month__text}>From last month</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  let res = await fetch(`${process.env.URL}/api/data`);
  let data = await res.json();

  return {
    props: { data },
  };
}

export default Home;
